# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Verge
email:
description: Verge is a secure and anonymous cryptocurrency, built with a focus on privacy.
url: "https://vergecurrency.com" # the base hostname & protocol for your site, e.g. http://example.com
enforce_ssl: https://vergecurrency.com
twitter_username: vergecurrency
github_username:  vergecurrency
twitter:
  username: vergecurrency

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
paginate_path: "blog/page:num/"
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock

# Verge Wallet Links
download:
  verge_wallet_windows        : 'https://github.com/vergecurrency/VERGE/releases/download/4.0stealth/VERGE-windows.zip'
  verge_wallet_macOS          : "https://github.com/vergecurrency/VERGE/releases/download/4.0stealth/VERGE-Qt-1-30-2018.dmg"
  # VERGE WALLET
  verge_wallet_arch           : "https://github.com/vergecurrency/VERGE/releases/download/2.1/arch_2.1.0.tar"
  verge_wallet_centos         : "https://github.com/vergecurrency/VERGE/releases/download/2.1/centos7_2.1.0.tar"
  verge_wallet_debian         : "https://github.com/vergecurrency/VERGE/releases/download/2.1/debian8_v2.1.0.tar"
  verge_wallet_fedora         : "https://github.com/vergecurrency/VERGE/releases/download/2.1/fedora23_2.1.0.tar"
  # MOBILE WALLET
  verge_wallet_android        : "https://play.google.com/store/apps/details?id=com.vergeandroid.wallet"
  coinomi_wallet_android      : "https://play.google.com/store/apps/details?id=com.coinomi.wallet"
  # ELECTRUM WALLET
  electrum_wallet_windows     : "https://github.com/vergecurrency/electrum-xvg/releases/download/2.4.1/electrum-xvg-win-amd64.zip"
  electrum_wallet_windows_tor : "https://github.com/vergecurrency/electrum-xvg-tor/releases/download/2.4.1/electrum-xvg-tor-win-amd64.zip"
  electrum_wallet_macOS       : "https://github.com/vergecurrency/electrum-xvg/releases/download/2.4/electrum-xvg-2.4-macosx.dmg"
  electrum_wallet_macOS_tor   : "https://github.com/vergecurrency/electrum-xvg-tor/releases/download/2.4/electrum-xvg-tor-2.4-macosx.dmg"
  electrum_wallet_linux       : "https://github.com/vergecurrency/electrum-xvg"
  electrum_wallet_linux_tor   : "https://github.com/vergecurrency/electrum-xvg-tor"
  # MISC WALLET
  verge_wallet_raspberry      : "https://github.com/vergecurrency/raspi/"
  verge_wallet_paper          : "https://vergecurrency.com/paper-wallet/"
  verge_wallet_docker         : "https://github.com/vergecurrency/Docker-Verge-Daemon/"
  verge_core_autoinstaller    : "https://github.com/vergecurrency/verge-core-installers"
  # WEB WALLET
  verge_wallet_web_tor        : "http://vcmlfg3fgsmy2teu.onion"
  verge_wallet_web_i2p        : "http://vhne4ia27avp7gtyltlj3fumq6ps343vap3gy3zqs7gj4yp2mbdq.b32.i2p/"

# Blog settings

# Lang settings
default_lang: 'en'
langs:
  'ar': 'العربية'
  'da': 'Dansk'
  'de': 'Deutsch'
  'en': 'English'
  'es': 'Español'
  'fr': 'Français'
  'id': 'Indonesia'
  'it': 'Italiano'
  'ja': '日本語'
  'pl': 'Polski'
  'ko': '한국의'
  'nl': 'Nederlands'
  'pt': 'Português'
  'ro': 'Română'
  'ru': 'Русский'
  'zh_CN': '简体中文'
  'zh_TW': '繁體中文'
lang_codes:
  - 'en'
  - 'es'
  - 'zh_CN'
  - 'ko'
  - 'nl'
  - 'ja'
  - 'pl'
  - 'da'
  - 'pt'
  - 'zh_TW'
  - 'ru'
  - 'fr'
  - 'it'
  - 'id'
  - 'de'
  - 'ar'
  - 'ro'
faq_lang_codes:
  - 'en'
  - 'ko'
  - 'de'
  - 'ru'
  - 'zh_CN'
  - 'id'
